export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const CREATE_NEW_POST = 'CREATE_NEW_POST';
export const HEADER_BUTTON_CLICK = 'HEADER_BUTTON_CLICK';
export const PUBLISH_POST = 'PUBLISH_POST';
export const SEARCH_POST = 'SEARCH_POST';
export const CLEAR_SEARCHTEXT = 'CLEAR_SEARCHTEXT';
